codecov:
  require_ci_to_pass: yes

comment:
  layout: "header, files, footer"
  hide_project_coverage: false
  behavior: default
  require_changes: false
  require_head: true
  require_base: false
  branches:
    - main

